CREATE DATABASE IF NOT EXISTS music DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE music;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sheets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    thumb_path VARCHAR(500) NOT NULL,
    bpm INT NOT NULL DEFAULT 80,
    beat_numerator INT NOT NULL DEFAULT 4,
    beat_denominator INT NOT NULL DEFAULT 4,
    sort_order INT NOT NULL DEFAULT 0,
    upload_user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FULLTEXT INDEX idx_title (title) WITH PARSER ngram,
    INDEX idx_sort_order (sort_order),
    FOREIGN KEY (upload_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert default user: jiangyiyi / 123456
-- Note: the password_hash here is generated by bcrypt for '123456'
INSERT INTO users (username, password_hash) 
VALUES ('jiangyiyi', '$2a$10$X8O0vE7/2W3p9i.5xM9yyeP/49eY2/w26tLw2eO1y32E04n9q0eK2')
ON DUPLICATE KEY UPDATE username=username;
